### ISSUE TITLE
ERR failed to establish connection

### ISSUE THREAD

**Issue by BernhardFuchs** [algorandfoundation/did-algo#102]
When deploying the driver to dev.uniresolver.io, it driver crashes after startup with the following error:

```
2024-01-09T08:22:00Z INF establishing connection to network agent: algo-did.aidtech.network:443
2024-01-09T08:22:05Z ERR failed to establish connection: failed to dial with context: context deadline exceeded
```

This triggers a `CrashLoopBackOff` on the Kubernetes Cluster and that's why we remove the driver for now https://github.com/decentralized-identity/universal-resolver/commit/32e079d453b90f441aca40927b9514a417f86fb9  
Once the issue are fixed, feel free to open a pull request to readd it.

**Comment by bcessa** [comment]
hi @BernhardFuchs thanks for the report, we are actively working on it.

**Comment by bcessa** [comment]
Hi @BernhardFuchs this PR https://github.com/decentralized-identity/universal-resolver/pull/409 should fix the issues and update the resolver driver to the latest version 👏🏼
