### ISSUE TITLE
What is the encoding format of private key in the did file?

### ISSUE THREAD

**Issue by thusithathilina** [algorandfoundation/did-algo#87]
I can see the private key is specified in the did file once a did is created. It seems base64 encoded. However, want to be confirmed the exact encoding of the private key. Is it first base64 decode and then base58 decode?

**Comment by thusithathilina** [comment]
Also is there a direct way of accessing the private key of a DID?

**Comment by bcessa** [comment]
The cryptographic keys used are registered on the DID document as "Verification Keys" according to the W3C specs. For example, in the case of Ed25519 an example would be:

```
{
  "@context": ["https://w3id.org/security/v1"],
  "id": "did:example:123456789abcdefghi#keys-1",
  "type": "Ed25519VerificationKey2018",
  "controller": "did:example:123456789abcdefghi",
  "expires": "2017-02-08T16:02:20Z",
  "publicKeyBase58" : "H3C2AVvLMv6gmMNam3uVAjZpfkcJCwDwnZn6z3wXmqPV"
}
```

> The `publicKeyBase58` property contains the raw public key bytes. The encoding is Base58 using the same alphabet as Bitcoin addresses and IPFS hashes.

Locally, we also store the private key portion under the `private` attribute; which is never published as part of the DID document. When locally encoding the `[]byte` for the private key the encoding used by default is base64.

The private key can easily be retrieved locally by inspecting the JSON file corresponding to the DID instance you are trying to inspect. For example, to retrieve a single private key for a DID with alias `sample` using [jq](https://stedolan.github.io/jq/) you can run something like:

```
cat $HOME/.algoid/sample | jq '.document.verificationMethod[].private'
```

_`$HOME/.algoid` is the default store path._

**Comment by thusithathilina** [comment]
Thank you very much for the clarification
