### ISSUE TITLE
UPDATES ON DID-ALGO for ALGO Projects

### ISSUE THREAD

**Issue by kcelestinomaria** [algorandfoundation/did-algo#94]
Came across this piece of work and had a couple of questions as I lead a project on Algorand where we need an identity system(https://jasiriprotocol.org), we are still on testnet and having a robust identity system is part of our needs at the moment:

**
1. What are the explicit goals of this DID system?
2. Is it scheduled for public production release anytime soon or in the future?
3. There is some work out there done on the same e.g Ceramic Network, Vendible(on Algorand) etc, already in mass use. How unique is this implementation and how is it customized for Algorand dAPPs and wallets if any? 
**

Looking forward to your response. Thanks!

@bcessa @fabrice102 @shaih @johnalanwoods

**Comment by pbennett** [comment]
NFDs (https://app.nf.domains) are used across all of Algorand already (66 integrations atm and supported in all wallets), are live on betanet, testnet, and mainnet, and provide as robust an identity solution as you'll find.  Support for multi-party linking, flexible ownership models, large (soon, near unlimited) arbitrary chain-accessible metadata storage, full forward and reverse on/off-chain lookups, global API, multiple off-chain verification attestations stored on-chain (email,twitter,telegram,discord,...).  
If desired, things like Vendible IDs for eg could just be metadata in the NFD, w/ NFDs being the discovery mechanism.

**Comment by pbennett** [comment]
Of course - it's an initial two-step mint / claim process, but the API is extremely simple to use.
https://api-docs.nf.domains/
Feel free to reach out in the #nfd-api channel on the NFD discord if you want info on minting, etc. but the openapi docs are linked from the docs as well where you can generate clients in about 15 languages.

**Comment by bcessa** [comment]
Hi @kcelestinomaria, let me provide a bit more context to your questions.
> 
> 1. What are the explicit goals of this DID system?

* Provide a chain-agnostic and general purpose platform for other projects requiring the use of "Decentralized Digital Identity" primitives.
* Ensure scalability and reusability via interoperability with existing standards and best-practices.

> 2. Is it scheduled for public production release anytime soon or in the future?
Is already in production and ready to use; you can:
* Review the products listed here https://www.aid.technology for examples of large scale production deployments using this tools today.
* Download the CLI application and get started.
* Read the tutorial for additional information on how to use it.
* If you require further assistance for a specific use-case, please let me know and I'll be glad to assist you.

> 3. There is some work out there done on the same e.g Ceramic Network, Vendible(on Algorand) etc, already in mass use. How unique is this implementation and how is it customized for Algorand dAPPs and wallets if any?
* The did-algo tools in this repo can be used with any wallet that supports the "wallet connect" protocol; for example the official Pera Wallet.

Finally yes, there are several other projects in the space, but as always, is very important to look closely at the details and decide what is the best solution based on your specific requirements. For example:

* To know more about the "Decentralized Identity" ecosystem as a whole, you can start reviewing the specs, standards, recommendations and tools available at: https://identity.foundation.
* There you'll find, among other tools, the official "Universal DID Resolver" hosted here: https://dev.uniresolver.io ; currently this is one of the best tools to ensure/validate DID interoperability and compliance with the latest specs. Which is a VERY important point to ensure QA, availability, security and usability of any project claiming to be based on this standards.
* Add the moment of writing this response: __of the 54 DID methods currently listed there, only 4 are compliant__. (`did:algo`, `did:cheqd`, `did:ebsi` and `did:oyd`)

I hope this is helpful, best regards.

<img width="1494" alt="Screenshot 2023-03-15 at 17 03 21" src="https://user-images.githubusercontent.com/259803/225464788-2bc59854-6bdf-469c-97c6-0efeeabb6ffb.png">

**Comment by bcessa** [comment]
I'll close this ticket since there's no actionable item related to it.
